// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ-0KR19wUm5HcWDkC_ZxcVwobqGw5mSU',
    appId: '1:46478635609:web:3e2297fe6660c84d373748',
    messagingSenderId: '46478635609',
    projectId: 'odkec-3445e',
    authDomain: 'odkec-3445e.firebaseapp.com',
    storageBucket: 'odkec-3445e.appspot.com',
    measurementId: 'G-74L49HRNLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlu8109vb0gKQfHMIuAA1w7yYMVudldXA',
    appId: '1:46478635609:android:306d4b86e64d3766373748',
    messagingSenderId: '46478635609',
    projectId: 'odkec-3445e',
    storageBucket: 'odkec-3445e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrp2EQpb7ZUCO-UxYqeB3_wN_Kjr9bT84',
    appId: '1:46478635609:ios:0b0fda6dc3d6bbcb373748',
    messagingSenderId: '46478635609',
    projectId: 'odkec-3445e',
    storageBucket: 'odkec-3445e.appspot.com',
    iosClientId: '46478635609-4esjpi6gl5lee5piop634n8uc2154bd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.odKec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrp2EQpb7ZUCO-UxYqeB3_wN_Kjr9bT84',
    appId: '1:46478635609:ios:0b0fda6dc3d6bbcb373748',
    messagingSenderId: '46478635609',
    projectId: 'odkec-3445e',
    storageBucket: 'odkec-3445e.appspot.com',
    iosClientId: '46478635609-4esjpi6gl5lee5piop634n8uc2154bd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.odKec',
  );
}
